### ISSUE TITLE
allow disabling generation of @spec on the overridable functions when using OnePiece.Commanded.ValueObject

### ISSUE THREAD

**Issue by jvantuyl** [straw-hat-team/beam-monorepo#98]
## Summary

When overriding a function that's `defoverridable`, there's no way to override the original type spec, only add to it.  This generates some really surprising behavior.

## Details

All of the problems I've encountered come from something as innocuous as this:
```elixir
defmodule MyErrorValue do
  use OnePiece.Commanded.ValueObject

  @type error_type() :: :busted | :broken | :angry
  @type error_reason() :: String.t()

  @type t() :: %__MODULE__{
    type: error_type(),
    reason: error_reason()
  }

  embedded_schema do
    field :type, Ecto.Enum, values: [:busted, :broken, :angry]
    field :reason, :string
  end

  @spec new(error_type()) :: t()
  def new(error_type) when is_atom(error_type) do
    %__MODULE__{type: error_type}
  end

  @spec new(error_type(), error_reason()) :: t()
  def new(error_type, error_reason) when is_atom(error_type) and is_binary(error_reason) do
    %__MODULE__{type: error_type, reason: reason}
  end
end
```

What is the spec of `new/1`?  Most people would think it's just what's on the screen.  But, in reality, it's:
```elixir
@spec new(map() | :busted | :broken | :angry) :: {:ok, t()} | {:error, any()} | t()
```

For extra fun, what's the spec of `new/2`?  Most people would think it's what's on the screen... and they'd be **right**.  And things get extra fun if you have a default argument, so you essentially define both arities of the function and they have wildly differing specs.

I also intentionally wrote in a subtle bug.  I "accidentally" messed up the return type from `new/1` (as this should either be a result tuple or we should be overriding `new!/1`).  Ideally Dialyzer would notice the spec not matching and complain.  What actually happens is you end up with a wildly permission, totally incorrect spec.  It will certainly allow more things that intended.  But also the real success typing can't handle the parameters it claims to.  And the result will only ever be one of the declared options.

For real fun, let's say you decide to accept a struct instead of an atom.  Now things get *really* weird.  This is because all structs are also maps.  Since there's already a spec that takes a map, another spec that takes a struct would "overlap" the possible inputs.  Dialyzer doesn't like this and complains about "overlapping domains".  In this case it just _*discards the spec completely*_ while emitting a rather cryptic warning.

## Analysis

Many developers probably aren't equipped to understand what's going on here.  The population of our community that fluently understands macros, speaks Dialyzer, and is likely to look at what `__using__` is even doing here is rather small.

On one hand, you don't even know that you're doing it.  If you override the function and add a new spec, the original spec is invisible unless you have some way to inspect it.  Most people won't even know that something is off unless something hints at it (i.e. an IDE popup or Dialyzer error).  In this way, it very much violates the [Rule of Least Surprise](https://en.wikipedia.org/wiki/Rule_of_least_surprise).

Since Dialyzer will believe you if you lie to it, it will further complicate things by hallucinating that the spec is meaningful.  Other times, it will notice that the success typing isn't correct either, thereby snapping back to reality in a way that isn't entirely helpful.

While the false warnings can be frustrating, the scarier thing is the _lack_ of certain warnings where there should be.  They get suppressed due to the odd but looser compound spec and the developer is none the wiser.

At the point that you get to the whole "overlapping domains" and "unsupported contract" stuff, most people are just lost.  The code they wrote *looks* simple.  They *think* they know what the spec is, because it's "right there in the file".  So far, most of the developers I've talked to had just ended up deciding that Dialyzer had been trying experimental drugs, shrugged, and moved on.

## Our Issues

While it's perhaps questionable whether it's wise to change a function to an incompatible type, I've found some places where it's been done in our codebase and it's pretty widespread.  I would not be surprised if other people run into this as well.  Unfortunately, the default response of many developers has been "just ignore Dialyzer".  😢 

### Solution Brainstorm

The easiest fix for me would be for `OnePiece` to just not generate the specs.  I think you can just take an option like `disable_type_generation: true`, put the `@spec` declarations inside of an `if` and it would just work.  I'd be glad to code this up if you'd accept it.

One other thought I had was to move the specs to the implementations in `ValueObject` instead of putting them in the generated code.  I'm pretty sure that Dialyzer would infer the typing through that function call and do essentially the same thing.  But, since the specs weren't on the generated function, specifying one would entirely subsume the inferred one.

This also makes it possible to override those functions with incompatible versions.  While that might not be wise, at least the spec wouldn't be subtly broken.

**Comment by yordis** [comment]
I regret placing the defoverridable there! I need the Elixir Type System already 😭 

---

Before we move on, could you share the **precise** scenarios where you felt the need to override? From what I observed, it seems like you're bypassing the value object invariants. If that's the case, it might be more straightforward not to use the Value Object. I would use `defstruct`. 

I'm eager to understand your approach better. My goal was to guide our budding team on best practices in Elixir. But it seems we've had some unintended situations.

I'm not suggesting you're incorrect. Just hoping for clarity, so we can have a constructive chat.

---

Also, could we focus more on practical scenarios and steer clear of too many hypotheticals?
I've noticed we often discuss situations that haven't occurred or perhaps weren't the intended use case. There are always intent and trade-offs behind the software. Sometimes, understanding them is required in order to leverage the tools effectively.

As well as, there are a lot of personal opinions being shared about the ecosystem and developers, which can be hard to address since they're based on personal perspectives and experiences.

I am familiar with your team, and all I ask is the understanding of how little time I had to properly train a team with literally **0 minutes of experience in Elixir**. So there are some pain points you will carry on, especially if you keep copy-pasting Jack's code 🤣 🤣 🤣 🤣 🤣 🤣 🤣 
People must learn programming languages and tools. We are not coding in ASM anymore, so they are a big deal of "I don't know what I am doing or how this works" already happening.

I would love to pair with you, and discuss so many things! Your experience is extremely valuable to me and I know that you are a freaking kool person, just that it is better to move that type of conversation/content to other methods of communication.

Please join Discord: https://discord.gg/5WURzBb I am always seeking to have fun and talk about tech until we pass out!

**Comment by yordis** [comment]
feel free to reopen the issue once more details are shared
